server:
  port: 8080    #应用端口   默认8080
  servlet:
    context-path: /manager    #请求接口的根路径 例如 http://localhost:8080/manager/
  tomcat:
    max-threads: 500          #tomcat起动的最大线程数，即同时处理的任务个数，默认值为200
    min-spare-threads: 10     #最小工作空闲线程数，默认10。
    max-connections: 500      #tomcat最大连接数
    accept-count: 5000       #当tomcat起动的线程数达到最大时，接受排队的请求个数，默认值为100
    max-http-post-size: 2097152    #通过POST上传的文件大小的最大值为2M（2097152）
    uri-encoding: UTF-8       #设定请求URI的解码字符集.
    #basedir: /data/   如果有上传文件的功能可以指定一个路径，临时路径 长时间不操作会失效

spring:
  profiles:
    active: '@env@'
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

# Mybatis配置
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configLocation: classpath:mybatis-config.xml

#pagehelper
pagehelper:
  helper-dialect: mysql   #分页语法采用的是mysql；oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
  reasonable: true   #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，
  params: pageNum=pageNum;pageSize=pageSize;count=countSql;  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值 ，默认：pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  supportMethodsArguments: true   #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  row-bounds-with-count: true